USE unireview;
-- SELECT count(*) FROM escuela;
-- CREACIÓN DE ESCUELAS
INSERT INTO escuela (idescuela, esc_nombre, esc_ubicacion, esc_enlace)
VALUES
(null, 'Instituto Tecnológico de Reynosa', 'Reynosa, Tamaulipas', 'https://www.reynosa.tecnm.mx/'),
(null,'Centro de Investigación y de Estudios Avanzados del Instituto Politécnico Nacional', 'Ciudad de México', 'https://www.cinvestav.mx/'),
(null,'Universidad Nacional Autónoma de México', 'Ciudad de México', 'https://www.unam.mx/'),
(null,'Instituto Tecnológico de Tláhuac', 'Ciudad de México', 'https://tlahuac2.tecnm.mx/'),
(null,'Escuela Superior de Educación Física', 'Ciudad de México', 'https://www.aefcm.gob.mx/dgenam/ESEF/'), 
(null,'Enseñanza e Investigación Superior, A.C. (UNIVERSIDAD TECMILENIO)', 'Guadalajara, Jalisco', 'https://www.tecmilenio.mx/es'),
(null, 'Instituto Tecnológico de Aguascalientes', 'Aguascalientes, Aguascalientes', 'https://aguascalientes.tecnm.mx/'),
(null, 'Universidad Autónoma de Aguascalientes', 'Aguascalientes, Aguascalientes', 'https://www.uaa.mx/portal/'),
(null, 'Universidad Politécnica de Aguascalientes', 'Aguascalientes, Aguascalientes', 'https://www.upa.edu.mx/'),
(null, 'Universidad Tecnológica de Aguascalientes', 'Aguascalientes, Aguascalientes', 'https://www.utags.edu.mx/'),
(null, 'Universidad Tecnológica de Calvillo', 'Calvillo, Aguascalientes', 'http://www.utcalvillo.edu.mx/'),
(null, 'Universidad Tecnológica del Norte de Aguascalientes', 'Rincón de Romos, Aguascalientes', 'https://www.utna.edu.mx/'),
(null, 'Centro de Enseñanza Técnica y Superior', 'Tijuana, Baja California', 'https://www.cetys.mx/'),
(null, 'Centro de Investigación Científica y de Educación Superior de Ensenada, Baja California', 'Ensenada, Baja California', 'https://www.cicese.edu.mx/'),
(null, 'El Colegio de la Frontera Norte, A.C.', 'Tijuana, Baja California', 'https://www.colef.mx/'),
(null, 'Instituto Tecnológico de Mexicali', 'Mexicali, Baja California', 'http://www.itmexicali.edu.mx/'),
(null, 'Instituto Tecnológico de Tijuana', 'Tijuana, Baja California', 'https://www.tijuana.tecnm.mx/'),
(null, 'Universidad Autónoma de Baja California', 'Mexicali, Baja California', 'http://www.uabc.mx/'),
(null, 'Centro de Investigaciones Biológicas del Noroeste, S.C.', 'La Paz, Baja California Sur', 'https://www.cibnor.gob.mx/'),
(null, 'Instituto Tecnológico de La Paz', 'La Paz, Baja California Sur', 'http://www.itlp.edu.mx'),
(null, 'Universidad Autónoma de Baja California Sur', 'La Paz, Baja California Sur', 'http://www.uabcs.mx'),
(null, 'Instituto Tecnológico de Campeche', 'Lerma, Campeche', 'https://itcampeche.edu.mx/'),
(null, 'Instituto Tecnológico de Chiná', 'Chiná, Campeche', 'http://www.itchina.edu.mx'),
(null, 'Instituto Tecnológico Superior de Champotón', 'Champotón, Campeche', 'https://champoton.tecnm.mx/'),
(null, 'Universidad Autónoma de Campeche', 'Campeche, Campeche', 'https://www.uacam.mx/'),
(null, 'Universidad Autónoma del Carmen', 'Ciudad del Carmen, Campeche', 'https://www.unacar.mx/'),
(null, 'El Colegio de la Frontera Sur', 'San Cristóbal de Las Casas, Chiapas (Sede)', 'https://www.ecosur.mx/'),
(null, 'Instituto Tecnológico de Tuxtla Gutiérrez', 'Tuxtla Gutiérrez, Chiapas', 'https://www.tuxtla.tecnm.mx/'),
(null, 'Universidad Autónoma de Chiapas', 'Tuxtla Gutiérrez, Chiapas', 'https://www.unach.mx/'),
(null, 'Universidad de Ciencias y Artes de Chiapas', 'Tuxtla Gutiérrez, Chiapas', 'https://www.unicach.mx/'),
(null, 'Universidad Politécnica de Chiapas', 'Suchiapa, Chiapas', 'https://www.upchiapas.edu.mx/'),
(null, 'Centro de Investigación en Materiales Avanzados, S.C.', 'Chihuahua, Chihuahua', 'https://cimav.edu.mx/'),
(null, 'Instituto Tecnológico de Chihuahua', 'Chihuahua, Chihuahua', 'https://itchihuahua.mx/'),
(null, 'Instituto Tecnológico de Chihuahua II', 'Chihuahua, Chihuahua', 'http://www.itchihuahuaii.edu.mx/'),
(null, 'Instituto Tecnológico de Ciudad Juárez', 'Ciudad Juárez, Chihuahua', 'http://cdjuarez.tecnm.mx/'),
(null, 'Instituto Tecnológico de Delicias', 'Delicias, Chihuahua', 'https://www.delicias.tecnm.mx/'),
(null, 'Instituto Tecnológico de Parral', 'Hidalgo del Parral, Chihuahua', 'http://www.itparral.edu.mx/'),
(null, 'Universidad Autónoma de Chihuahua', 'Chihuahua, Chihuahua', 'https://uach.mx/'),
(null, 'Universidad Autónoma de Ciudad Juárez', 'Ciudad Juárez, Chihuahua', 'https://www.uacj.mx/'),
(null, 'Universidad Tecnológica de Chihuahua', 'Chihuahua, Chihuahua', 'http://www.utch.edu.mx/'),
(null, 'Centro de Investigación en Ciencias de Información Geoespacial', 'Aguascalientes, Aguascalientes', 'http://www.centrogeo.org.mx/'),
(null, 'Centro de Investigación y Docencia Económicas, A.C.', 'Ciudad de México (Sede)', 'https://www.cide.edu/'),
(null, 'Centro de Investigaciones y Estudios Superiores en Antropología Social', 'San Cristóbal de Las Casas, Chiapas (Sede)', 'https://ciesas.edu.mx'),
(null, 'El Colegio de México, A.C.', 'Ciudad de México', 'https://www.colmex.mx/'),
(null, 'Escuela Nacional de Antropología e Historia', 'Ciudad de México', 'https://www.enah.edu.mx'),
(null, 'Escuela Nacional de Conservación, Restauración y Museografía “Manuel del Castillo Negrete', 'Ciudad de México', 'http://www.encrym.edu.mx/'),
(null, 'Facultad Latinoamericana de Ciencias Sociales', 'Ciudad de México (Sede)', 'https://www.flacso.edu.mx/'),
(null, 'Instituto de Investigaciones Dr. José María Luis Mora', 'Ciudad de México', 'https://www.institutomora.edu.mx/Inicio.html'),
(null, 'Instituto Nacional de Bellas Artes y Literatura', 'Ciudad de México', 'https://inba.gob.mx/'),
(null, 'Instituto Politécnico Nacional', 'Ciudad de México', 'https://www.ipn.mx/'),
(null, 'Instituto Tecnológico Autónomo de México', 'Ciudad de México', 'https://www.itam.mx/'),
(null, 'Instituto Tecnológico de Iztapalapa', 'Ciudad de México', 'https://www.iztapalapa.tecnm.mx/'),
(null, 'Instituto Tecnológico de Iztapalapa II', 'Ciudad de México', 'https://iztapalapa2.tecnm.mx/'),
(null, 'Universidad Autónoma de la Ciudad de México', 'Ciudad de México', 'http://www.uacm.edu.mx/'),
(null, 'Universidad Autónoma Metropolitana', 'Ciudad de México (Sede)', 'https://www.uam.mx/'),
(null, 'Universidad de Las Américas, A.C., Ciudad de México', 'Ciudad de México', 'https://www.udlacdmx.mx/ver3/'),
(null, 'Universidad del Claustro de Sor Juana, A.C.', 'Ciudad de México', 'https://elclaustro.mx/'),
(null, 'Universidad del Valle de México', 'Ciudad de México (Sede)', 'https://www.universidaduvm.mx/'),
(null, 'Universidad Iberoamericana, A.C.', 'Ciudad de México', 'https://ibero.mx/'),
(null, 'Universidad Insurgentes', 'Ciudad de México (Sede)', 'http://www.universidadinsurgentes.edu.mx'),
(null, 'Universidad Intercontinental', 'Ciudad de México', 'https://www.uic.mx/'),
(null, 'Universidad La Salle, A.C.', 'Ciudad de México', 'https://lasalle.mx/'),
(null, 'Universidad Panamericana', 'Ciudad de México (Sede)', 'https://www.up.edu.mx/es'),
(null, 'Universidad Pedagógica Nacional', 'Ciudad de México (Sede)', 'https://www.upn.mx/'),
(null, 'Universidad Tecnológica de México', 'Ciudad de México (Sede)', 'https://www.unitec.mx/'),
(null, 'Instituto Tecnológico de La Laguna', 'Torreón, Coahuila', 'http://www.itlalaguna.edu.mx'),
(null, 'Instituto Tecnológico de Piedras Negras', 'Piedras Negras, Coahuila', 'http://www.piedrasnegras.tecnm.mx'),
(null, 'Instituto Tecnológico de Saltillo', 'Saltillo, Coahuila', 'https://saltillo.tecnm.mx/'),
(null, 'Universidad Autónoma Agraria Antonio Narro', 'Saltillo, Coahuila', 'https://www.uaaan.edu.mx/'),
(null, 'Universidad Autónoma de Coahuila', 'Saltillo, Coahuila', 'http://www.uadec.mx/'),
(null, 'Universidad Autónoma de La Laguna, A.C.', 'Torreón, Coahuila', 'https://www.ual.mx/'),
(null, 'Universidad Tecnológica de Coahuila', 'Ramos Arizpe, Coahuila', 'https://www.utc.edu.mx/'),
(null, 'Instituto Tecnológico de Colima', 'Villa de Álvarez, Colima', 'https://www.colima.tecnm.mx/'),
(null, 'Universidad de Colima', 'Colima, Colima (Sede)', 'https://www.ucol.mx/'),
(null, 'Instituto Tecnológico de Durango', 'Durango, Durango', 'https://www.itdurango.edu.mx/'),
(null, 'Universidad Juárez del Estado de Durango', 'Durango, Durango (Sede)', 'https://www.ujed.mx/'),
(null, 'Centro de Investigaciones en Óptica, A.C.', 'León, Guanajuato (Sede)', 'https://www.cio.mx/'),
(null, 'Instituto Tecnológico de Celaya', 'Celaya, Guanajuato', 'https://celaya.tecnm.mx/'),
(null, 'Instituto Tecnológico de León', 'León, Guanajuato', 'https://leon.tecnm.mx/'),
(null, 'Instituto Tecnológico de Roque', 'Roque, Guanajuato', 'http://roque.tecnm.mx/'),
(null, 'Instituto Tecnológico Superior de Irapuato', 'Irapuato, Guanajuato (Sede)', 'https://irapuato.tecnm.mx/'),
(null, 'Universidad de Celaya', 'Celaya, Guanajuato', 'https://www.udec.edu.mx/'),
(null, 'Universidad de Guanajuato', 'Guanajuato, Guanajuato (Sede)', 'https://www.ugto.mx/'),
(null, 'Universidad Iberoamericana León', 'León, Guanajuato', 'https://www.iberoleon.mx/'),
(null, 'Universidad Politécnica de Juventino Rosas', 'Juventino Rosas, Guanajuato', 'http://www.upjr.edu.mx/'),
(null, 'Universidad Tecnológica de León', 'León, Guanajuato (Sede)', 'http://www.utleon.edu.mx/'),
(null, 'Universidad Tecnológica del Suroeste de Guanajuato', 'Valle de Santiago, Guanajuato', 'http://www.utsoe.edu.mx/'),
(null, 'Universidad Virtual del Estado de Guanajuato', 'Purísima del Rincón, Guanajuato (Sede)', 'https://uveg.edu.mx/'),
(null, 'Instituto Tecnológico de Acapulco', 'Acapulco de Juárez, Guerrero', 'https://acapulco.tecnm.mx/'),
(null, 'Universidad Autónoma de Guerrero', 'Chilpancingo, Guerrero (Sede)', 'https://www.uagro.mx/'),
(null, 'Universidad Hipócrates', 'Acapulco de Juárez, Guerrero', 'https://www.uhipocrates.edu.mx/'),
(null, 'Instituto Tecnológico de Huejutla', 'Huejutla de Reyes, Hidalgo', 'https://huejutla.tecnm.mx/'),
(null, 'Instituto Tecnológico de Pachuca', 'Pachuca de Soto, Hidalgo', 'http://www.itpachuca.edu.mx'),
(null, 'Instituto Tecnológico Latinoamericano', 'Mineral de la Reforma, Hidalgo (Sede)', 'https://www.itla.edu.mx/'),
(null, 'Instituto Tecnológico Superior de Huichapan', 'Huichapan, Hidalgo', 'https://www.iteshu.edu.mx/iteshu/'),
(null, 'Instituto Tecnológico Superior del Occidente del Estado de Hidalgo', 'Mixquiahuala de Juárez, Hidalgo', 'http://www.itsoeh.edu.mx/'),
(null, 'Instituto Tecnológico Superior del Oriente del Estado de Hidalgo', 'Apan, Hidalgo', 'https://www.itesa.edu.mx/'),
(null, 'Universidad Autónoma del Estado de Hidalgo', 'Pachuca de Soto, Hidalgo (Sede)', 'https://www.uaeh.edu.mx/'),
(null, 'Universidad Politécnica de Tulancingo', 'Tulancingo de Bravo, Hidalgo', 'http://www.upt.edu.mx/'),
(null, 'Universidad Politécnica Metropolitana de Hidalgo', 'Tolcayuca, Hidalgo', 'http://www.upmetropolitana.edu.mx/'),
(null, 'Universidad Tecnológica de Tula-Tepeji', 'Tula de Allende, Hidalgo', 'https://www.uttt.edu.mx/'),
(null, 'Centro de Enseñanza Técnica Industrial', 'Guadalajara, Jalisco (Sede)', 'https://www.ceti.mx/cetinew/'),
(null, 'Instituto Tecnológico de Ciudad Guzmán', 'Ciudad Guzmán, Jalisco', 'http://www.cdguzman.tecnm.mx/pag/'),
(null, 'Instituto Tecnológico y de Estudios Superiores de Occidente, A.C.', 'Tlaquepaque, Jalisco', 'https://www.iteso.mx/'),
(null, 'Universidad Autónoma de Guadalajara', 'Zapopan, Jalisco', 'https://www.uag.mx/'),
(null, 'Universidad de Guadalajara', 'Guadalajara, Jalisco (Sede)', 'https://www.udg.mx/');

INSERT INTO escuela (idescuela, esc_nombre, esc_ubicacion, esc_enlace)
VALUES
(null, 'Universidad del Valle de Atemajac', 'Zapopan, Jalisco', 'https://www.univa.mx/'),
(null, 'Universidad Tecnológica de Jalisco', 'Guadalajara, Jalisco', 'https://www.utj.edu.mx/'),
(null, 'Colegio de Postgraduados', 'Texcoco, Estado de México (Sede)', 'https://www.colpos.mx/wb/'),
(null, 'Escuela Judicial del Estado de México', 'Toluca, Estado de México', 'http://www.pjedomex.gob.mx/ejem/'),
(null, 'Escuela Normal de Jilotepec', 'Jilotepec, Estado de México', 'https://normaljilotepec.edomex.gob.mx/'),
(null, 'Escuela Normal de Teotihuacán', 'San Juan Teotihuacán, Estado de México', 'https://normalteotihuacan.edomex.gob.mx/'),
(null, 'Escuela Normal de Texcoco', 'Texcoco, Estado de México', 'https://normaltexcoco.edomex.gob.mx/'),
(null, 'Escuela Normal de Tlalnepantla', 'Tlalnepantla, Estado de México', 'https://normaltlalnepantla.edomex.gob.mx'),
(null, 'Escuela Normal de Zumpango', 'Zumpango, Estado de México', 'https://normalzumpango.edomex.gob.mx/'),
(null, 'Escuela Normal No. 1 de Toluca', 'Toluca, Estado de México', 'https://normal1toluca.edomex.gob.mx/'),
(null, 'Escuela Normal No. 3 de Nezahualcóyotl', 'Nezahualcóyotl, Estado de México', 'https://normal3neza.edomex.gob.mx/'),
(null, 'Instituto Tecnológico de Tlalnepantla', 'Tlalnepantla, Estado de México', 'http://www.tlalnepantla.tecnm.mx/'),
(null, 'Instituto Tecnológico de Toluca', 'Toluca, Estado de México', 'https://toluca.tecnm.mx/'),
(null, 'Tecnológico de Estudios Superiores de Chalco', 'Chalco, Estado de México', 'https://tescha.edomex.gob.mx/'),
(null, 'Tecnológico de Estudios Superiores de Chimalhuacán', 'Chimalhuacán, Estado de México', 'https://teschi.edu.mx/'),
(null, 'Tecnológico de Estudios Superiores de Cuautitlán Izcalli', 'Cuautitlán Izcalli, Estado de México', 'https://tesci.edomex.gob.mx/'),
(null, 'Tecnológico de Estudios Superiores de Ecatepec', 'Ecatepec de Morelos, Estado de México', 'http://www.tese.edu.mx/'),
(null, 'Tecnológico de Estudios Superiores de Jilotepec', 'Jilotepec, Estado de México', 'http://tesji.edomex.gob.mx/'),
(null, 'Tecnológico de Estudios Superiores de San Felipe del Progreso', 'San Felipe del Progreso, Estado de México', 'https://tessfp.edomex.gob.mx/'),
(null, 'Tecnológico de Estudios Superiores del Oriente del Estado de México', 'La Paz, Estado de México', 'https://tesoem.edomex.gob.mx/'),
(null, 'Universidad Anáhuac México', 'Huixquilucan, Estado de México (Sede)', 'https://www.anahuac.mx/mexico/'),
(null, 'Universidad Autónoma Chapingo', 'Texcoco, Estado de México', 'https://www.chapingo.mx/'),
(null, 'Universidad Autónoma del Estado de México', 'Toluca, Estado de México (Sede)', 'https://www.uaemex.mx/'),
(null, 'Universidad Estatal del Valle de Ecatepec', 'Ecatepec de Morelos, Estado de México', 'https://www.uneve.edu.mx/'),
(null, 'Universidad Politécnica del Valle de México', 'Tultitlán, Estado de México', 'https://upvm.edomex.gob.mx/'),
(null, 'Universidad Tecnológica de Nezahualcóyotl', 'Nezahualcóyotl, Estado de México', 'http://www.utn.edu.mx/'),
(null, 'Universidad Tecnológica de Tecámac', 'Tecámac, Estado de México', 'https://uttecamac.edomex.gob.mx/'),
(null, 'Universidad Tecnológica del Valle de Toluca', 'Zinacantepec, Estado de México', 'https://utvt.edomex.gob.mx/'),
(null, 'Universidad Tecnológica Fidel Velázquez', 'Tlalnepantla, Estado de México', 'http://utfv.edomex.gob.mx/'),
(null, 'El Colegio de Michoacán, A.C.', 'Zamora, Michoacán', 'https://www.umich.mx/'),
(null, 'Instituto Tecnológico de Jiquilpan', 'Jiquilpan, Michoacán', 'http://www.jiquilpan.tecnm.mx/'),
(null, 'Instituto Tecnológico de La Piedad', 'La Piedad, Michoacán', 'https://piedad.tecnm.mx/'),
(null, 'Instituto Tecnológico de Morelia', 'Morelia, Michoacán', 'https://www.morelia.tecnm.mx/'),
(null, 'Instituto Tecnológico de Zitácuaro', 'Zitácuaro, Michoacán', 'https://portal.itzitacuaro.edu.mx/'),
(null, 'Universidad Michoacana de San Nicolás de Hidalgo', 'Morelia, Michoacán (Sede)', 'https://www.umich.mx/'),
(null, 'Centro Nacional de Investigación y Desarrollo Tecnológico', 'Cuernavaca, Morelos', 'https://cenidet.tecnm.mx/'),
(null, 'Instituto Nacional de Salud Pública', 'Cuernavaca, Morelos', 'https://www.insp.mx/'),
(null, 'Instituto Tecnológico de Cuautla', 'Cuautla, Morelos', 'https://www.cuautla.tecnm.mx/'),
(null, 'Instituto Tecnológico de Zacatepec', 'Zacatepec, Morelos', 'http://www.itzacatepec.edu.mx/'),
(null, 'Universidad Autónoma del Estado de Morelos', 'Cuernavaca, Morelos (Sede)', 'https://www.uaem.mx/'),
(null, 'Universidad Tecnológica Emiliano Zapata del Estado de Morelos', 'Emiliano Zapata, Morelos', 'http://www.utez.edu.mx/'),
(null, 'Instituto Tecnológico de Tepic', 'Tepic, Nayarit', 'https://www.tepic.tecnm.mx/'),
(null, 'Universidad Autónoma de Nayarit', 'Tepic, Nayarit (Sede)', 'http://www.uan.edu.mx'),
(null, 'Centro de Estudios Universitarios Monterrey', 'Monterrey, Nuevo León', 'https://www.universidadceu.mx/'),
(null, 'Instituto Tecnológico de Linares', 'Linares, Nuevo León', 'http://www.itlinares.edu.mx'),
(null, 'Instituto Tecnológico de Nuevo León', 'Guadalupe, Nuevo León', 'http://www.itnl.edu.mx'),
(null, 'Instituto Tecnológico y de Estudios Superiores de Monterrey', 'Monterrey, Nuevo León (Sede)', 'https://tec.mx/es'),
(null, 'Universidad Autónoma de Nuevo León', 'San Nicolás de los Garza, Nuevo León (Sede)', 'https://www.uanl.mx/'),
(null, 'Universidad de Montemorelos', 'Montemorelos, Nuevo León', 'https://www.um.edu.mx/'),
(null, 'Universidad de Monterrey', 'San Pedro Garza García, Nuevo León', 'https://www.udem.edu.mx/es'),
(null, 'Universidad Regiomontana, A.C.', 'Monterrey, Nuevo León', 'https://www.u-erre.mx/'),
(null, 'Instituto Tecnológico de Oaxaca', 'Oaxaca de Juárez, Oaxaca', 'http://www.itoaxaca.edu.mx/'),
(null, 'Instituto Tecnológico de Tuxtepec', 'San Juan Bautista Tuxtepec, Oaxaca', 'https://www.tuxtepec.tecnm.mx/'),
(null, 'Instituto Tecnológico del Istmo', 'Ciudad Ixtepec, Oaxaca', 'https://istmo.tecnm.mx/'),
(null, 'Universidad Autónoma Benito Juárez de Oaxaca', 'Oaxaca de Juárez, Oaxaca (Sede)', 'http://www.uabjo.mx/'),
(null, 'Universidad de la Sierra Juárez', 'Ixtlán de Juárez, Oaxaca', 'http://www.unsij.edu.mx/'),
(null, 'Universidad de la Sierra Sur', 'Miahuatlán de Porfirio Díaz, Oaxaca', 'http://www.unsis.edu.mx/'),
(null, 'Benemérita Universidad Autónoma de Puebla', 'Puebla, Puebla (Sede)', 'http://www.buap.mx/'),
(null, 'Escuela Normal Superior Federalizada del Estado de Puebla', 'Puebla, Puebla', 'http://ensfep.com.mx/'),
(null, 'Fundación Universidad de Las Américas, Puebla', 'San Andrés Cholula, Puebla (Sede)', 'https://www.udlap.mx/web/'),
(null, 'Instituto Nacional de Astrofísica, Óptica y Electrónica', 'Tonantzintla, Puebla', 'https://www.inaoep.mx/'),
(null, 'Instituto Tecnológico de Puebla', 'Puebla, Puebla', 'https://www.puebla.tecnm.mx/'),
(null, 'Instituto Tecnológico de Tehuacán', 'Tehuacán, Puebla', 'http://www.ittehuacan.edu.mx/'),
(null, 'Instituto Tecnológico Superior de Acatlán de Osorio', 'Acatlán de Osorio, Puebla', 'http://www.itsao.edu.mx/'),
(null, 'Instituto Tecnológico Superior De Atlixco', 'Atlixco, Puebla', 'https://atlixco.tecnm.mx/inicio.php'),
(null, 'Instituto Tecnológico Superior de La Sierra Norte de Puebla', 'Xicotepec de Juárez, Puebla', 'https://www.itssnp.edu.mx/'),
(null, 'Instituto Tecnológico Superior de San Martín Texmelucan', 'San Martín Texmelucan, Puebla', 'http://www.itssmt.edu.mx/'),
(null, 'Instituto Tecnológico Superior de Teziutlán', 'Teziutlán, Puebla', 'https://teziutlan.tecnm.mx/'),
(null, 'Instituto Tecnológico Superior de Zacapoaxtla', 'Zacapoaxtla, Puebla', 'https://zacapoaxtla.tecnm.mx/'),
(null, 'Universidad Anáhuac Puebla', 'San Andrés Cholula, Puebla (Sede)', 'https://www.anahuac.mx/puebla/'),
(null, 'Universidad de la Sierra, A.C.', 'Huauchinango, Puebla', 'https://usac.edu.mx/'),
(null, 'Universidad de Oriente', 'Tehuacán, Puebla', 'https://www.uo.edu.mx/inicio'),
(null, 'Universidad Del Valle De Puebla', 'Puebla, Puebla', 'https://www.uvp.mx/'),
(null, 'Universidad Iberoamericana Puebla', 'Puebla, Puebla (Sede)', 'https://www.iberopuebla.mx/'),
(null, 'Universidad Popular Autónoma del Estado de Puebla', 'Puebla, Puebla (Sede)', 'https://www.upaep.mx/'),
(null, 'Universidad Tecnológica de Huejotzingo', 'Huejotzingo, Puebla', 'https://www.uth.edu.mx/'),
(null, 'Universidad Tecnológica de Puebla', 'Puebla, Puebla', 'http://www.utpuebla.edu.mx/'),
(null, 'Universidad Tecnológica de Tecamachalco', 'Tecamachalco, Puebla', 'https://uttecam.edu.mx/html/'),
(null, 'Universidad Tecnológica de Tehuacán', 'Tehuacán, Puebla', 'https://www.uttehuacan.edu.mx/web/'),
(null, 'Universidad Tecnológica de Xicotepec de Juárez', 'Xicotepec de Juárez, Puebla', 'http://www.utxicotepec.edu.mx/'),
(null, 'Centro de Investigación y Desarrollo Tecnológico en Electroquímica, S.C.', 'Pedro Escobedo, Querétaro (Sede)', 'https://www.cideteq.mx/'),
(null, 'Instituto Tecnológico de Querétaro', 'Querétaro, Querétaro', 'https://queretaro.tecnm.mx/'),
(null, 'Universidad Autónoma de Querétaro', 'Querétaro, Querétaro (Sede)', 'https://www.uaq.mx/'),
(null, 'Universidad Tecnológica de Querétaro', 'Querétaro, Querétaro', 'https://www.uteq.edu.mx/'),
(null, 'Universidad Tecnológica de San Juan del Río', 'San Juan del Río, Querétaro', 'https://utsjr.edu.mx/'),
(null, 'Instituto Tecnológico de Cancún', 'Cancún, Quintana Roo', 'https://www.cancun.tecnm.mx/'),
(null, 'Instituto Tecnológico de Chetumal', 'Chetumal, Quintana Roo', 'http://www.itchetumal.edu.mx'),
(null, 'Universidad Autónoma del Estado de Quintana Roo', 'Chetumal, Quintana Roo (Sede)', 'https://www.uqroo.mx/'),
(null, 'Universidad del Caribe', 'Cancún, Quintana Roo', 'https://www.unicaribe.mx/'),
(null, 'Benemérita y Centenaria Escuela Normal del Estado de San Luis Potosí', 'San Luis Potosí, San Luis Potosí (Sede)', 'http://beceneslp.edu.mx/pagina/'),
(null, 'Instituto Potosino de Investigación Científica y Tecnológica, A.C.', 'San Luis Potosí, San Luis Potosí (Sede)', 'https://www.ipicyt.edu.mx/'),
(null, 'Instituto Tecnológico de Ciudad Valles', 'Ciudad Valles, San Luis Potosí', 'http://www.tecvalles.mx/web/'),
(null, 'Instituto Tecnológico de Matehuala', 'Matehuala, San Luis Potosí', 'https://matehuala.tecnm.mx/'),
(null, 'Instituto Tecnológico de San Luis Potosí', 'San Luis Potosí, San Luis Potosí', 'https://slp.tecnm.mx/directivos/'),
(null, 'Instituto Tecnológico Superior de San Luis Potosí, Capital', 'San Luis Potosí, San Luis Potosí', 'https://slpotosicapital.tecnm.mx//'),
(null, 'Universidad Autónoma de San Luis Potosí', 'San Luis Potosí, San Luis Potosí (Sede)', 'http://www.uaslp.mx'),
(null, 'Instituto Tecnológico de Culiacán', 'Culiacán, Sinaloa', 'https://culiacan.tecnm.mx/'),
(null, 'Instituto Tecnológico de Los Mochis', 'Los Mochis, Sinaloa', 'https://www.mochis.tecnm.mx/'),
(null, 'Universidad Autónoma de Occidente', 'Culiacán, Sinaloa (Sede)', 'https://uadeo.mx/'),
(null, 'Universidad Autónoma de Sinaloa', 'Culiacán, Sinaloa (Sede)', 'https://www.uas.edu.mx/');

INSERT INTO escuela (idescuela, esc_nombre, esc_ubicacion, esc_enlace)
VALUES
(null, 'Centro de Investigación en Alimentación y Desarrollo, A.C.', 'Hermosillo, Sonora (Sede)', 'https://www.ciad.mx/'),
(null, 'El Colegio de Sonora', 'Hermosillo, Sonora (Sede)', 'https://www.colson.edu.mx/'),
(null, 'Instituto Tecnológico de Hermosillo', 'Hermosillo, Sonora', 'http://www.ith.mx'),
(null, 'Instituto Tecnológico de Nogales', 'Nogales, Sonora', 'http://nogales.tecnm.mx/index.asp'),
(null, 'Instituto Tecnológico de Sonora', 'Ciudad Obregón, Sonora (Sede)', 'https://www.itson.mx/Paginas/index.aspx'),
(null, 'Instituto Tecnológico Superior de Cajeme', 'Ciudad Obregón, Sonora', 'https://www.itesca.edu.mx/'),
(null, 'Universidad de Sonora', 'Hermosillo, Sonora (Sede)', 'https://www.unison.mx/'),
(null, 'Universidad Estatal de Sonora', 'Hermosillo, Sonora', 'https://www.ues.mx/'),
(null, 'Universidad Tecnológica de Hermosillo', 'Hermosillo, Sonora', 'http://www.uthermosillo.edu.mx/'),
(null, 'Universidad Tecnológica del Sur de Sonora', 'Benito Juárez (Etchojoa), Sonora', 'https://uts.sonora.gob.mx/'),
(null, 'Instituto Tecnológico de Villahermosa', 'Villahermosa, Tabasco', 'http://villahermosa.tecnm.mx/site/'),
(null, 'Instituto Tecnológico Superior de Villa La Venta', 'Huimanguillo, Tabasco', 'http://laventa.tecnm.mx/'),
(null, 'Universidad Juárez Autónoma de Tabasco', 'Villahermosa, Tabasco (Sede)', 'https://www.ujat.mx/'),
(null, 'Instituto Tecnológico de Ciudad Madero', 'Ciudad Madero, Tamaulipas', 'http://www.cdmadero.tecnm.mx'),
(null, 'Instituto Tecnológico de Ciudad Victoria', 'Ciudad Victoria, Tamaulipas', 'http://www.itvictoria.edu.mx'),
(null, 'Instituto Tecnológico de Matamoros', 'Matamoros, Tamaulipas', 'https://www.itmatamoros.edu.mx/'),
(null, 'Instituto Tecnológico de Nuevo Laredo', 'Nuevo Laredo, Tamaulipas', 'https://nlaredo.tecnm.mx/'),
(null, 'U.P.N. Unidad 285 Reynosa', 'Reynosa, Tamaulipas', 'http://www.upn285.edu.mx'),
(null, 'Universidad Autónoma de Tamaulipas', 'Ciudad Victoria, Tamaulipas (Sede)', 'https://www.uat.edu.mx/'),
(null, 'Universidad del Noreste, A.C.', 'Tampico, Tamaulipas', 'https://www.une.edu.mx/es/'),
(null, 'Instituto Tecnológico de Apizaco', 'Apizaco, Tlaxcala', 'http://www.itapizaco.edu.mx'),
(null, 'Universidad Autónoma de Tlaxcala', 'Tlaxcala, Tlaxcala (Sede)', 'https://uatx.mx/'),
(null, 'Instituto de Ecología, A.C.', 'Xalapa, Veracruz (Sede)', 'https://www.inecol.mx/inecol/index.php/es/'),
(null, 'Instituto Tecnológico de Minatitlán', 'Minatitlán, Veracruz', 'http://www.itmina.edu.mx'),
(null, 'Instituto Tecnológico de Orizaba', 'Orizaba, Veracruz', 'http://www.orizaba.tecnm.mx'),
(null, 'Instituto Tecnológico de Veracruz', 'Veracruz, Veracruz', 'http://www.veracruz.tecnm.mx'),
(null, 'Instituto Tecnológico Superior de Misantla', 'Misantla, Veracruz', 'https://misantla.tecnm.mx/'),
(null, 'Instituto Tecnológico Superior de Poza Rica', 'Poza Rica, Veracruz', 'http://www.itspozarica.edu.mx/'),
(null, 'Instituto Tecnológico Superior de Tantoyuca', 'Tantoyuca, Veracruz', 'https://itsta.edu.mx/'),
(null, 'Instituto Tecnológico Superior de Zongolica', 'Zongolica, Veracruz', 'https://zongolica.tecnm.mx/TecNM/'),
(null, 'Universidad Cristóbal Colón', 'Veracruz, Veracruz', 'http://www.ucc.mx'),
(null, 'Universidad Tecnológica de Gutiérrez Zamora', 'Gutiérrez Zamora, Veracruz', 'https://utgz.edu.mx/'),
(null, 'Universidad Veracruzana', 'Xalapa, Veracruz (Sede)', 'https://www.uv.mx/'),
(null, 'Centro de Investigación Científica de Yucatán, A.C.', 'Mérida, Yucatán (Sede)', 'https://www.cicy.mx/'),
(null, 'Instituto Tecnológico de Mérida', 'Mérida, Yucatán', 'https://www.merida.tecnm.mx/'),
(null, 'Instituto Tecnológico Superior Progreso', 'Progreso, Yucatán', 'http://www.progreso.tecnm.mx/'),
(null, 'Universidad Autónoma de Yucatán', 'Mérida, Yucatán (Sede)', 'https://www.uady.mx/'),
(null, 'Instituto Tecnológico de Zacatecas', 'Guadalupe, Zacatecas', 'https://zacatecas.tecnm.mx/'),
(null, 'Universidad Autónoma de Zacatecas (Francisco García Salinas)', 'Zacatecas, Zacatecas (Sede)', 'http://www.uaz.edu.mx');